### ISSUE TITLE
Remove double validation password

### ISSUE THREAD

**Issue by Japoivvb** [nsaladie/MP13-Hospital-Nurses-API#38]
https://github.com/nsaladie/MP13-Hospital-BackEnd/blob/18f355a72803b65054011c85d04a765bd391be7a/src/main/java/com/example/Hospital/Hospital/NurseController.java#L39

if nurseRepository.findByNameAndPassword is already searching by name and password, check again password is not required in controller layer

**Comment by nsaladie** [comment]
With these changes, the double validation of the password is removed.
It validates that the database password and the user password are case-sensitive, this change is compatible with the Mysql database but may not be compatible with other databases.
